name: Build XenonRecomp for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Ninja
      run: choco install ninja

    - name: Configure CMake with Clang
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -DCMAKE_C_COMPILER=clang-cl `
          -DCMAKE_CXX_COMPILER=clang-cl `
          -G Ninja


    - name: Build with CMake (Ninja)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 4  # Parallel build with 4 jobs

    - name: Copy Required Header File
      run: copy XenonUtils\ppc_context.h build\

    - name: List Build Directory Contents
      run: dir ${{github.workspace}}/build  # Windows command to list files

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: XenonRecomp-Windows
        path: ${{github.workspace}}/build
